# Generated by Django 3.2 on 2022-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='check_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='check_out',
            field=models.IntegerField(),
        ),
    ]
